import { createSlice } from '@reduxjs/toolkit'

// Define an initial state for the list of invoices
const initialState = {
  invoices: [],
}

// Define a slice for the list of invoices
const InvoiceSlice = createSlice({
  name: 'invoices',
  initialState,
  reducers: {
    // Add an invoice to the list
    addInvoice: (state, action) => {
      const invoiceNumbers = state.invoices.map(invoice => invoice.invoiceNumber);
      const maxInvoiceNumber = Math.max(...invoiceNumbers)>0?Math.max(...invoiceNumbers):0;
      const newInvoice = { ...action.payload, invoiceNumber: maxInvoiceNumber + 1,isOpen:false };
      state.invoices.push(newInvoice);
    },    
    // Edit an invoice in the list
    editInvoice: (state, action) => {
      const index = state.invoices.findIndex(invoice => invoice.invoiceNumber === action.payload.invoiceNumber)
      if (index !== -1) {
        state.invoices[index] = action.payload
      }
    },
    // Delete an invoice from the list
    deleteInvoice: (state, action) => {
      state.invoices = state.invoices.filter(invoice => invoice.invoiceNumber !== action.payload)
    },
  }
})

// Export the actions and reducer generated by the slice
export const { addInvoice, editInvoice, deleteInvoice } = InvoiceSlice.actions
export default InvoiceSlice.reducer